(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CITY_VIEWS=['Bengaluru','Chennai','Mumbai','Delhi','Gujarat','Hyderabad','Kerala','Pune','Ranchi','Vijaywada'];
const PRODUCT_LABELS={HL:'HL – Home Loan',LAP:'LAP – Loan Against Property',PL:'PL – Personal Loan',BL:'BL – Business Loan',OTHER:'Other Products'};
const SEQ_DEFAULT=['Public|Spot','Public|MIS','Private|Spot','Private|MIS','NBFC|Spot','NBFC|MIS'];
const PRESETS={compact:{margin:5,font:7.4,line:1.10,fieldGap:.5,blockGap:.8,header:10,footer:16,qrGap:1.3,cardPadding:1,sectionGap:1.2},standard:{margin:8,font:8.4,line:1.26,fieldGap:1,blockGap:1.4,header:12,footer:22,qrGap:2.5,cardPadding:1.5,sectionGap:2.2},spacious:{margin:10,font:9.2,line:1.42,fieldGap:1.8,blockGap:2.2,header:14,footer:26,qrGap:3.5,cardPadding:2,sectionGap:3.2}};
const state={records:[],schemaVersion:'',user:null,token:sessionStorage.getItem('catalogToken')||'',view:'public',city:'Bengaluru',factor:null,cap:null,display:'list',filters:{product:'',payment:'',city:''},search:'',selected:new Set(),sequence:[...SEQ_DEFAULT],print:{...PRESETS.compact,orientation:'landscape'},pdfStyle:'',previewTimer:null,logoManifest:null};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function meaningful(v){return v!==null&&v!==undefined&&String(v).trim()!==''&&String(v).trim()!=='-';}
function initials(name){return String(name||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function currentTier(){if(state.view==='raw')return 'RAW'; if(state.view==='t2')return 'T2'; if(state.view==='city')return /^Vijaywada$/i.test(state.city)?'T2':'T1'; return state.view==='t1'?'T1':'';}
function currentCap(){return currentTier()==='T2'?85:90;}
function canDownload(){return !!state.user && state.view!=='raw' && state.view!=='public';}
function apiHeaders(){return state.token?{Authorization:`Bearer ${state.token}`}:{}}
async function jsonFetch(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j;}

async function devFallback(view='public',factor=null){
  if(!['localhost','127.0.0.1',''].includes(location.hostname)) throw new Error('Catalog API unavailable');
  const raw=await (await fetch('api/_data/catalog-data.json')).json();
  const cls=await (await fetch('api/_data/institution-classification.json')).json();
  const cap=view==='t2'?85:90, f=factor==null?cap:Math.min(cap,Number(factor));
  const recs=raw.records.map(r=>({...r,institutionClass:cls[r.institutionName]||'NBFC',payoutDisplay:view==='raw'?r.maxBankSlab:view==='public'?'':localTransform(r.maxBankSlab,f),factor:view==='raw'?null:f,tier:view==='raw'?'RAW':view.toUpperCase()}));
  return {ok:true,schemaVersion:raw.schemaVersion,view,factor:view==='raw'?null:f,cap:view==='raw'?null:cap,records:recs};
}
function localFloor(n){let x=Math.floor((n+1e-10)*100)/100;if(Math.floor((x+1e-10)*100)%10===1)x=Math.floor((x-.01+1e-10)*100)/100;return x;}
function localTransform(source,factor){let t=String(source||'');const protectedShares=[];t=t.replace(/(\d+(?:\.\d+)?)\s*%\s+of\s+(the\s+)?(PF|processing\s+fee)(\s+collected)?/gi,(m,n,the,basis,col)=>{const v=parseFloat(n)*factor/100;const token=`__S${protectedShares.length}__`;protectedShares.push(`${String((Math.round(v*100)/100).toFixed(2)).replace(/\.00$/,'').replace(/(\.\d*[1-9])0+$/,'$1')}% of ${the||''}${basis}${col||''}`);return token});t=t.replace(/(\d+(?:\.\d+)?)\s*%/g,(m,n)=>`${localFloor(parseFloat(n)*factor/100).toFixed(2)}%`);t=t.replace(/Payout\s*=\s*PF\s*Collected/gi,`Payout = ${factor}% of PF Collected`).replace(/DSA\s+Payout\s*=\s*PF\s*collected/gi,`DSA Payout = ${factor}% of PF collected`).replace(/Processing\s+Fee\s*=\s*Payout/gi,`Payout = ${factor}% of Processing Fee`).replace(/\bor\s+PF\s+collected\b/gi,`or ${factor}% of PF collected`);protectedShares.forEach((v,i)=>t=t.replace(`__S${i}__`,v));return t;}

async function loadCatalog(view=state.view,factor=null){
  let apiView=view;
  if(view==='city') apiView=/^Vijaywada$/i.test(state.city)?'t2':'t1';
  const q=new URLSearchParams({view:apiView}); if(view==='city')q.set('city',state.city); if(factor!=null)q.set('factor',factor);
  try{const j=await jsonFetch(`/api/catalog?${q}`,{headers:apiHeaders()});applyCatalog(j,view);}catch(e){try{const j=await devFallback(apiView,factor);applyCatalog(j,view);}catch(e2){$('#source-status').textContent=`Catalog failed to load: ${e.message}`;}}
}
function applyCatalog(j,requestedView){const studioOpen=$('#download-overlay')?.classList.contains('open');const dlCity=studioOpen?($('#download-city-filter')?.value||''):'';state.records=j.records||[];state.schemaVersion=j.schemaVersion||'';state.view=requestedView;state.factor=j.factor;state.cap=j.cap;if(!studioOpen)state.selected.clear();buildFilters();if(studioOpen&&dlCity)$('#download-city-filter').value=dlCity;renderInternalSwitcher();renderAll();$('#source-status').innerHTML=`<span class="status-dot"></span>${state.records.length} current product records · ${new Set(state.records.map(r=>r.institutionName)).size} institutions · Sheet1 source`;}

function mainRecords(){return state.records.filter(r=>r.thirdPartyProvider!=='FinWizz');}
function finWizzRecords(){return state.records.filter(r=>r.thirdPartyProvider==='FinWizz');}
function visibleRecords(){const q=state.search.trim().toLowerCase();return mainRecords().filter(r=>{if(state.filters.product&&r.productGroup!==state.filters.product)return false;if(state.filters.payment&&r.paymentType!==state.filters.payment)return false;if(state.filters.city&&r.applicableCities!==state.filters.city)return false;if(q){const hay=[r.institutionName,r.code,r.productType,r.variant,r.applicableCities,r.payoutTimeline,r.conditions].filter(Boolean).join(' ').toLowerCase();if(!hay.includes(q))return false;}return true;});}
function groupBanks(records){const map=new Map();records.forEach(r=>{if(!map.has(r.institutionName))map.set(r.institutionName,[]);map.get(r.institutionName).push(r)});return [...map.entries()].map(([name,recs])=>({name,records:recs.sort((a,b)=>a.productGroup.localeCompare(b.productGroup)||a.variant.localeCompare(b.variant))})).sort((a,b)=>a.name.localeCompare(b.name));}
function conditionInfo(recs){const counts=new Map();recs.forEach(r=>{if(meaningful(r.conditions)){const k=r.conditions.trim();counts.set(k,(counts.get(k)||0)+1)}});const shared=[...counts.entries()].filter(([,n])=>n>1).map(([c])=>c);const per=new Map();recs.forEach(r=>{if(meaningful(r.conditions)&&!shared.includes(r.conditions.trim()))per.set(r.id,r.conditions.trim())});return {shared,per};}
function unique(arr){return [...new Set(arr.filter(meaningful))]}

function buildFilters(){const products=['HL','LAP','PL','BL','OTHER'];const payments=['Spot','MIS'];const cities=unique(mainRecords().map(r=>r.applicableCities)).sort((a,b)=>a.localeCompare(b));$('#filter-cluster').innerHTML=`<label class="filter-control"><span>Product</span><select id="product-filter"><option value="">All products</option>${products.map(v=>`<option value="${v}">${PRODUCT_LABELS[v]}</option>`).join('')}</select></label><label class="filter-control"><span>Payment basis</span><select id="payment-filter"><option value="">Spot + MIS</option>${payments.map(v=>`<option>${v}</option>`).join('')}</select></label><label class="filter-control"><span>Applicable Cities</span><select id="city-filter"><option value="">All city values</option>${cities.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;$('#product-filter').value=state.filters.product;$('#payment-filter').value=state.filters.payment;$('#city-filter').value=state.filters.city;$('#product-filter').onchange=e=>{state.filters.product=e.target.value;renderAll()};$('#payment-filter').onchange=e=>{state.filters.payment=e.target.value;renderAll()};$('#city-filter').onchange=e=>{state.filters.city=e.target.value;renderAll()};const dl=$('#download-city-filter');dl.innerHTML=`<option value="">All applicable-city values</option>${cities.map(v=>`<option>${esc(v)}</option>`).join('')}`;}
function renderInternalSwitcher(){const box=$('#internal-switcher'),tabs=$('#view-tabs'),cityPicker=$('#city-view-picker');if(!state.user){box.classList.add('hidden');return}box.classList.remove('hidden');const list=state.user.role==='shiv'?[['raw','Raw'],['t1','T1'],['t2','T2'],['city','City-wise']]:[['t1','T1'],['t2','T2'],['city','City-wise']];tabs.innerHTML=list.map(([v,l])=>`<button class="view-tab ${state.view===v?'active':''}" data-internal-view="${v}">${l}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>switchView(b.dataset.internalView));cityPicker.classList.toggle('hidden',state.view!=='city');$('#city-view-select').innerHTML=CITY_VIEWS.map(c=>`<option ${c===state.city?'selected':''}>${c}</option>`).join('');$('#city-view-select').onchange=e=>{state.city=e.target.value;loadCatalog('city')};}
async function switchView(v){if(v==='raw'&&state.user?.role!=='shiv')return;state.filters={product:'',payment:'',city:''};state.factor=null;await loadCatalog(v);}
function viewLabel(){if(state.view==='public')return 'Public Catalog · payouts hidden';if(state.view==='raw')return 'Shiv · Raw Max Slab · view only';if(state.view==='city')return `${state.city} · ${currentTier()} logic`;return `${currentTier()} · ${state.factor}% payout basis`;}

function bankCard(bank){const info=conditionInfo(bank.records);const products=unique(bank.records.map(r=>r.productGroup));const codes=unique(bank.records.map(r=>r.code)).join(' · ');const payouts=unique(bank.records.map(r=>r.payoutDisplay));const payment=unique(bank.records.map(r=>r.paymentType));const selectable=canDownload();const shared=info.shared[0]||'';return `<article class="bank-card ${state.display==='list'?'list-card':'grid-card'}" data-bank="${esc(bank.name)}"><div class="bank-seal">${esc(initials(bank.name))}</div><div><div class="bank-name">${esc(bank.name)}</div><div class="bank-sub">${esc(codes)}</div></div><div class="bank-middle"><div class="product-chip-row">${products.map(p=>`<span class="chip">${esc(PRODUCT_LABELS[p]||p)}</span>`).join('')}${payment.map(p=>`<span class="chip ${p==='Spot'?'spot':''}">${esc(p)}</span>`).join('')}${payouts.map(p=>`<span class="chip payout">${esc(p)}</span>`).join('')}</div><div class="bank-sub">${esc(unique(bank.records.map(r=>r.applicableCities)).join(' · '))}</div></div><div class="bank-shared-snippet">${shared?esc(shared):'Product-specific conditions available in details.'}</div><div class="card-actions">${selectable?`<label class="select-bank"><input type="checkbox" data-select-bank="${esc(bank.name)}" ${state.selected.has(bank.name)?'checked':''}> Select</label>`:''}<button class="details-btn" data-details="${esc(bank.name)}">View details</button></div></article>`;}
function renderCatalog(){const banks=groupBanks(visibleRecords());$('#catalog').className=`catalog ${state.display}-mode`;$('#catalog').innerHTML=banks.map(bankCard).join('');$('#empty-state').classList.toggle('hidden',banks.length>0);$('#result-count').textContent=`Showing ${banks.length} institutions · ${visibleRecords().length} product records`;$('#active-view-label').textContent=viewLabel();$('#catalog').querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>openDetails(b.dataset.details));$('#catalog').querySelectorAll('[data-select-bank]').forEach(ch=>ch.onchange=()=>{ch.checked?state.selected.add(ch.dataset.selectBank):state.selected.delete(ch.dataset.selectBank);renderSelection()});}
function renderSelection(){const allowed=canDownload();$('#selection-row').classList.toggle('hidden',!allowed);$('#download-fab').classList.toggle('hidden',!allowed);$('#selection-count').textContent=`${state.selected.size} selected`;}
function renderFinWizz(){const rows=finWizzRecords();const panel=$('#finwizz-panel');const allow=state.user?.role==='shiv';panel.classList.toggle('hidden',!(allow&&rows.length));if(!(allow&&rows.length))return;$('#finwizz-list').innerHTML=rows.map(r=>`<div class="third-party-row"><b>${esc(r.institutionName)}</b><span>${esc(PRODUCT_LABELS[r.productGroup]||r.productGroup)}</span><span>${esc(r.code)}</span><span>${esc(r.variant)}${r.payoutDisplay?` · ${esc(r.payoutDisplay)}`:''}</span></div>`).join('');}
function renderAll(){renderCatalog();renderSelection();renderFinWizz();renderInternalSwitcher();}

function openDetails(name){const recs=mainRecords().filter(r=>r.institutionName===name);const info=conditionInfo(recs);$('#detail-content').innerHTML=`<div class="detail-head"><div class="bank-seal">${esc(initials(name))}</div><div><h2>${esc(name)}</h2><div class="detail-meta">${unique(recs.map(r=>r.paymentType)).map(x=>`<span class="chip ${x==='Spot'?'spot':''}">${esc(x)}</span>`).join('')}${unique(recs.map(r=>r.applicableCities)).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></div></div>${info.shared.length?`<div class="shared-conditions"><b>Bank-level payout conditions</b>${info.shared.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<div class="detail-products">${recs.map(r=>`<section class="product-card"><h3>${esc(PRODUCT_LABELS[r.productGroup]||r.productGroup)} · ${esc(r.variant)}</h3><div class="field-grid">${field('Code',r.code)}${field('Gross / Net',r.grossNet)}${field('Payout',r.payoutDisplay)}${field('Top Slab Loan Value',r.topSlabLoanVal)}${field('Payout Timeline',r.payoutTimeline,true)}${field('Applicable Cities',r.applicableCities,true)}${info.per.has(r.id)?field('Product-specific conditions',info.per.get(r.id),true):''}${field('Login Mandate / Process',r.loginProcess,true)}${field('Payout Capping',r.payoutCapping,true)}${field('Clawback',r.clawback,true)}</div></section>`).join('')}</div>`;openOverlay('detail-overlay');}
function field(label,value,wide=false){if(!meaningful(value))return '';return `<div class="field ${wide?'wide':''}"><b>${esc(label)}</b><span>${esc(value)}</span></div>`;}
function openOverlay(id){const el=$('#'+id);el.classList.add('open');el.setAttribute('aria-hidden','false')}
function closeOverlay(id){const el=$('#'+id);el.classList.remove('open');el.setAttribute('aria-hidden','true')}

async function login(){const id=$('#auth-id').value.trim(),password=$('#auth-password').value;$('#auth-error').textContent='';try{const j=await jsonFetch('/api/auth',{method:'POST',body:JSON.stringify({id,password})});state.user=j.user;state.token=j.token;sessionStorage.setItem('catalogToken',state.token);closeOverlay('auth-overlay');$('#login-btn').classList.add('hidden');$('#logout-btn').classList.remove('hidden');await loadCatalog('t1');}catch(e){if(['localhost','127.0.0.1',''].includes(location.hostname)&&((id==='Team'&&password==='Team@123')||(id==='Shiv'&&password==='1399'))){state.user={id,role:id==='Shiv'?'shiv':'team',label:id==='Shiv'?'Shiv':'Team Internal'};state.token='dev';sessionStorage.setItem('catalogToken','dev');closeOverlay('auth-overlay');$('#login-btn').classList.add('hidden');$('#logout-btn').classList.remove('hidden');await loadCatalog('t1');}else $('#auth-error').textContent=e.message;}}
async function restoreSession(){if(!state.token)return false;try{const j=await jsonFetch('/api/auth',{headers:apiHeaders()});state.user=j.user;$('#login-btn').classList.add('hidden');$('#logout-btn').classList.remove('hidden');return true}catch(e){sessionStorage.removeItem('catalogToken');state.token='';return false}}
async function logout(){state.user=null;state.token='';sessionStorage.removeItem('catalogToken');$('#login-btn').classList.remove('hidden');$('#logout-btn').classList.add('hidden');state.filters={product:'',payment:'',city:''};await loadCatalog('public');}

function selectedBanks(){const vis=groupBanks(visibleRecords()).map(b=>b.name);return state.selected.size?[...state.selected]:vis;}
function selectedRecordsForDownload(){const banks=new Set(selectedBanks());let recs=mainRecords().filter(r=>banks.has(r.institutionName));const cf=$('#download-city-filter')?.value||'';if(cf)recs=recs.filter(r=>r.applicableCities===cf);return recs;}
function sequenceCounts(recs){const map={};groupDownloadEntries(recs).forEach(e=>map[e.sequenceKey]=(map[e.sequenceKey]||0)+1);return map;}
function groupDownloadEntries(recs){const by=new Map();recs.forEach(r=>{const cls=r.institutionClass||'NBFC', key=`${cls}|${r.paymentType}`;const id=`${key}|${r.institutionName}`;if(!by.has(id))by.set(id,{institution:r.institutionName,sequenceKey:key,records:[]});by.get(id).records.push(r)});return [...by.values()];}
function orderedEntries(recs){const rank=new Map(state.sequence.map((k,i)=>[k,i]));return groupDownloadEntries(recs).sort((a,b)=>(rank.get(a.sequenceKey)??99)-(rank.get(b.sequenceKey)??99)||a.institution.localeCompare(b.institution));}
function renderSequencer(){const counts=sequenceCounts(selectedRecordsForDownload());$('#sequence-list').innerHTML=state.sequence.map(k=>`<div class="sequence-row" draggable="true" data-seq="${k}"><span class="drag">⋮⋮</span><b>${esc(k.replace('|',' · '))}</b><small>${counts[k]||0} banks</small></div>`).join('');let drag='';$$('.sequence-row').forEach(row=>{row.ondragstart=()=>drag=row.dataset.seq;row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const target=row.dataset.seq;if(!drag||drag===target)return;const a=state.sequence.indexOf(drag),b=state.sequence.indexOf(target);state.sequence.splice(a,1);state.sequence.splice(b,0,drag);renderSequencer();schedulePreview()}})}

function loadPrintSettings(){try{const j=JSON.parse(localStorage.getItem('catalogPrintSettings')||'null');if(j)state.print={...state.print,...j}}catch(e){}}
function savePrintSettings(){localStorage.setItem('catalogPrintSettings',JSON.stringify(state.print))}
function syncPrintInputs(){const p=state.print;$('#s-margin').value=p.margin;$('#s-font').value=p.font;$('#s-line').value=p.line;$('#s-field-gap').value=p.fieldGap;$('#s-block-gap').value=p.blockGap;$('#s-header').value=p.header;$('#s-footer').value=p.footer;$('#s-qr-gap').value=p.qrGap;$('#s-card-padding').value=p.cardPadding;$('#s-section-gap').value=p.sectionGap;$$('input[name="orientation"]').forEach(x=>x.checked=x.value===p.orientation);$$('[data-preset]').forEach(x=>x.classList.toggle('active',x.dataset.preset===p.preset));}
function readPrintInputs(){state.print={...state.print,preset:'custom',margin:+$('#s-margin').value,font:+$('#s-font').value,line:+$('#s-line').value,fieldGap:+$('#s-field-gap').value,blockGap:+$('#s-block-gap').value,header:+$('#s-header').value,footer:+$('#s-footer').value,qrGap:+$('#s-qr-gap').value,cardPadding:+$('#s-card-padding').value,sectionGap:+$('#s-section-gap').value,orientation:$('input[name="orientation"]:checked').value};savePrintSettings();schedulePreview()}
function setPreset(name){state.print={...PRESETS[name],orientation:state.print.orientation,preset:name};savePrintSettings();syncPrintInputs();schedulePreview()}

function openDownloadStudio(){if(!canDownload())return;if(!state.selected.size){const visible=groupBanks(visibleRecords());if(!visible.length)return alert('No institutions are available to download.');if(!confirm(`No banks are selected. Use all ${visible.length} visible institutions?`))return;visible.forEach(b=>state.selected.add(b.name));renderSelection();}state.factor=state.factor??currentCap();$('#factor-input').max=currentCap();$('#factor-input').value=state.factor;$('#factor-cap').textContent=`Maximum ${currentCap()}% for ${currentTier()}`;$('#pdf-style-card').classList.toggle('hidden',state.user?.role!=='shiv');$('#shiv-cover-card').classList.toggle('hidden',state.user?.role!=='shiv');state.pdfStyle=state.user?.role==='shiv'?'':'simple';$$('input[name="pdf-style"]').forEach(x=>x.checked=false);$('#network-consent').checked=false;syncPrintInputs();renderSequencer();openOverlay('download-overlay');renderPreview();updateDownloadButton();}
function updateDownloadButton(){const format=$('input[name="download-format"]:checked')?.value||'pdf';const styleOk=format==='xlsx'||state.user?.role!=='shiv'||!!state.pdfStyle;const consent=$('#network-consent').checked;$('#final-download').disabled=!(styleOk&&consent&&selectedRecordsForDownload().length);$('#final-download').textContent=format==='xlsx'?'Download Excel':'Download PDF';$('#print-design-card').classList.toggle('hidden',format==='xlsx'||state.pdfStyle==='rich');}
let previewTimer;function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(renderPreview,180)}
function previewRows(recs){return orderedEntries(recs).slice(0,state.print.orientation==='landscape'?6:8)}
function renderPreview(){if(!$('#download-overlay').classList.contains('open'))return;const recs=selectedRecordsForDownload();const format=$('input[name="download-format"]:checked')?.value||'pdf';const shivPdf=format==='pdf'&&state.user?.role==='shiv';if(shivPdf&&!state.pdfStyle){$('#preview-meta').textContent='Choose Simple PDF or Rich PDF to preview';$('#preview-shell').innerHTML='<div class="preview-page"><h4>Choose a PDF style</h4><p class="muted">Simple PDF prioritizes compact output. Rich PDF uses the branded cover, fixed Partner Benefits page and bank-table design.</p></div>';$('#download-summary').textContent=`${new Set(recs.map(r=>r.institutionName)).size} institutions · ${recs.length} product records`;updateDownloadButton();return;}const rich=state.user?.role==='shiv'&&state.pdfStyle==='rich'&&format==='pdf';const entries=previewRows(recs);const groups=orderedEntries(recs);let pages;if(format==='xlsx')pages=2;else if(rich)pages=2+Math.ceil(groups.length/(state.print.orientation==='landscape'?5:6));else pages=2+Math.max(1,Math.ceil(groups.length/(state.print.orientation==='landscape'?6:8)));$('#preview-meta').textContent=format==='xlsx'?`${recs.length} product rows · 2 worksheets`:`Approx. ${pages} pages · ${groups.length} bank entries`;$('#download-summary').textContent=`${new Set(recs.map(r=>r.institutionName)).size} institutions · ${recs.length} product records · ${currentTier()} ${state.factor}%`;if(format==='xlsx'){$('#preview-shell').innerHTML=`<div class="preview-page"><h4>Master Catalog ${monthStamp()}</h4><p class="muted">Excel workbook preview</p>${miniTable(entries)}</div>`}else if(rich){$('#preview-shell').innerHTML=`<div><div class="preview-page rich ${state.print.orientation==='portrait'?'portrait':''}"><h4 style="text-align:center;margin-top:20%">MASTER CATALOG</h4><p style="text-align:center">${monthStamp()}</p></div><div class="preview-page" style="background:url('assets/partner-benefits.jpg') center/cover no-repeat"></div><div class="preview-page rich ${state.print.orientation==='portrait'?'portrait':''}"><h4 style="text-align:center">MASTER CATALOG</h4><h4 style="text-align:center;font-size:13px">${esc(entries[0]?.sequenceKey?.replace('|',' · ')||'BANKS')}</h4>${miniTable(entries,true)}<p class="rich-note">Official logos load only when supplied in assets/bank-logos.</p></div></div>`}else{$('#preview-shell').innerHTML=`<div class="preview-page ${state.print.orientation==='portrait'?'portrait':''}"><h4>Master Catalog ${monthStamp()}</h4>${miniTable(entries)}</div>`}updateDownloadButton()}
function miniTable(entries,rich=false){return `<table class="preview-mini-table"><thead><tr><th>Bank</th><th>Code</th><th>Products</th><th>Payout dates</th><th>Conditions</th><th>City</th></tr></thead><tbody>${entries.map(e=>{const i=conditionInfo(e.records),p=e.records.map(r=>`${r.productGroup} ${r.payoutDisplay||''}`).join(' · ');return `<tr><td>${esc(e.institution)}</td><td>${esc(unique(e.records.map(r=>r.code)).join(', '))}</td><td>${esc(p)}</td><td>${esc(unique(e.records.map(r=>r.payoutTimeline)).join(' · ').slice(0,130))}</td><td>${esc((i.shared[0]||e.records[0]?.conditions||'').slice(0,180))}</td><td>${esc(unique(e.records.map(r=>r.applicableCities)).join(' · '))}</td></tr>`}).join('')}</tbody></table>`}

async function refreshForFactor(){const value=Math.max(0,Math.min(currentCap(),Number($('#factor-input').value)||0));$('#factor-input').value=value;state.factor=value;await loadCatalog(state.view==='city'?'city':state.view,value);renderSequencer();schedulePreview();}
async function getNetworkStamp(){try{return await jsonFetch('/api/network-stamp')}catch(e){return {ip:'Unavailable',timestamp:new Date().toISOString()}}}
function monthStamp(){return new Intl.DateTimeFormat('en-US',{month:'short',year:'2-digit'}).format(new Date()).replace(' ','-')}
function fileBase(){return `Master Catalog ${monthStamp()}`}
async function lazyScript(src,globalName){if(globalName&&window[globalName])return window[globalName];return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=()=>resolve(globalName?window[globalName]:true);s.onerror=reject;document.head.appendChild(s)})}
async function fetchDataUrl(url){const r=await fetch(url);if(!r.ok)throw new Error(url);const blob=await r.blob();return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob)})}
async function loadRaster(url){return new Promise(async(resolve)=>{try{const r=await fetch(url);if(!r.ok)return resolve(null);const blob=await r.blob();const obj=URL.createObjectURL(blob);const im=new Image();im.onload=()=>{const c=document.createElement('canvas');const scale=Math.min(1,300/Math.max(im.width,im.height));c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(obj);resolve(c.toDataURL('image/png'))};im.onerror=()=>resolve(null);im.src=obj}catch(e){resolve(null)}})}
async function logoForInstitution(name){if(!state.logoManifest){try{state.logoManifest=await (await fetch('assets/bank-logo-manifest.json')).json()}catch(e){state.logoManifest={}}}const slug=state.logoManifest[name];if(!slug)return null;for(const ext of ['svg','png','webp','jpg']){const d=await loadRaster(`assets/bank-logos/${slug}.${ext}`);if(d)return d}return null}

function wrap(doc,text,width,fontSize){doc.setFontSize(fontSize);return doc.splitTextToSize(String(text||''),width)}
function auditText(stamp){const dt=new Date(stamp.timestamp||Date.now());return {ip:stamp.ip||'Unavailable',date:dt.toLocaleDateString(),time:dt.toLocaleTimeString(),tz:Intl.DateTimeFormat().resolvedOptions().timeZone||'Local'};}
function addSimpleHeader(doc,pageW,settings,title){const m=settings.margin;doc.setFont('helvetica','bold');doc.setFontSize(Math.max(8,settings.font+1));doc.text(title,m,m+4);doc.setDrawColor(30);doc.line(m,m+settings.header,pageW-m,m+settings.header)}
function drawSimpleBank(doc,entry,y,pageW,pageH,settings){const m=settings.margin,w=pageW-2*m,pad=settings.cardPadding;const recs=entry.records,ci=conditionInfo(recs);const textParts=[];recs.forEach(r=>textParts.push(`${r.productGroup} · ${r.variant} · ${r.payoutDisplay||'—'} · ${r.code}`));const conditions=[...ci.shared,...recs.filter(r=>ci.per.has(r.id)).map(r=>`${r.variant}: ${ci.per.get(r.id)}`)].join('\n');const summary=[textParts.join('\n'),`Payout dates: ${unique(recs.map(r=>r.payoutTimeline)).join(' | ')}`,conditions?`Conditions: ${conditions}`:'',`City: ${unique(recs.map(r=>r.applicableCities)).join(' | ')}`,meaningful(recs[0].clawback)?`Clawback: ${unique(recs.map(r=>r.clawback)).join(' | ')}`:''].filter(Boolean).join('\n');const lines=wrap(doc,summary,w-(pad*2+4),settings.font);const lineFactor=settings.line+(settings.fieldGap/Math.max(1,settings.font*.3528));const h=Math.max(17,7+pad*2+lines.length*(settings.font*.3528*lineFactor));if(y+h>pageH-settings.footer){doc.addPage('a4',settings.orientation);const sz=doc.internal.pageSize;addSimpleHeader(doc,sz.getWidth(),settings,'Master Catalog');y=m+settings.header+5}doc.setDrawColor(205);doc.roundedRect(m,y,w,h,2,2);doc.setFont('helvetica','bold');doc.setFontSize(settings.font+1);doc.text(entry.institution,m+pad+2,y+pad+3.5);doc.setFont('helvetica','normal');doc.setFontSize(settings.font);doc.text(lines,m+pad+2,y+pad+8,{lineHeightFactor:lineFactor});return y+h+settings.blockGap+settings.sectionGap;}
async function generateSimplePdf(recs,stamp){await lazyScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js','jspdf');const {jsPDF}=window.jspdf;const o=state.print.orientation;const doc=new jsPDF({unit:'mm',format:'a4',orientation:o,compress:true});const p=state.print;let pageW=doc.internal.pageSize.getWidth(),pageH=doc.internal.pageSize.getHeight();const name=state.user?.role==='shiv'?$('#cover-name').value.trim():'NoBroker Loans Team',desig=state.user?.role==='shiv'?$('#cover-designation').value.trim():'Internal Team';doc.setFont('helvetica','bold');doc.setFontSize(26);doc.text('MASTER CATALOG',pageW/2,pageH*.42,{align:'center'});doc.setFontSize(13);doc.text(monthStamp(),pageW/2,pageH*.49,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text([name,desig].filter(Boolean).join(' · '),pageW/2,pageH*.56,{align:'center'});doc.addPage('a4',o);pageW=doc.internal.pageSize.getWidth();pageH=doc.internal.pageSize.getHeight();const a=auditText(stamp);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text('Download Verification',pageW/2,35,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(12);doc.text(`Public IP: ${a.ip}`,25,65);doc.text(`Date: ${a.date}`,25,77);doc.text(`Time: ${a.time}`,25,89);doc.text(`Timezone: ${a.tz}`,25,101+p.qrGap);doc.setFontSize(8);doc.text('This stamp is generated at download time for catalog verification.',25,118+p.qrGap);doc.addPage('a4',o);pageW=doc.internal.pageSize.getWidth();pageH=doc.internal.pageSize.getHeight();addSimpleHeader(doc,pageW,p,`Master Catalog · ${currentTier()} · ${state.factor}%`);let y=p.margin+p.header+5;orderedEntries(recs).forEach(e=>{y=drawSimpleBank(doc,e,y,pageW,pageH,p)});return doc;}

function shortText(s,n){s=String(s||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s}
function entrySummary(entry){const ci=conditionInfo(entry.records);const payouts=entry.records.map(r=>`${r.productGroup} ${r.variant}: ${r.payoutDisplay||'—'}`).join(' • ');const shared=ci.shared.join(' • ');const specific=entry.records.filter(r=>ci.per.has(r.id)).map(r=>`${r.variant}: ${ci.per.get(r.id)}`).join(' • ');return {payouts,conditions:[shared,specific].filter(Boolean).join(' • '),timeline:unique(entry.records.map(r=>r.payoutTimeline)).join(' • '),city:unique(entry.records.map(r=>r.applicableCities)).join(' • '),code:unique(entry.records.map(r=>r.code)).join(' / '),type:unique(entry.records.map(r=>r.grossNet)).join(' / ')};}
async function addRichBackground(doc,bg,orientation){const w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();doc.addImage(bg,'JPEG',0,0,w,h,undefined,'FAST')}
async function drawRichGroupPage(doc,entries,groupTitle,assets,orientation){const w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();await addRichBackground(doc,assets.bg,orientation);doc.setTextColor(0);doc.setFont('helvetica','bold');doc.setFontSize(19);doc.text('MASTER CATALOG',w/2,18,{align:'center'});doc.setFontSize(13);doc.text(groupTitle.replace('|',' · ').toUpperCase(),w/2,28,{align:'center'});const m=10,tableTop=34,footerH=21,tableH=h-tableTop-footerH-5,rows=entries.length,rowH=tableH/Math.max(rows,1);const cols=orientation==='landscape'?[18,32,28,20,46,90,35]:[16,28,23,18,36,60,29];const scale=(w-2*m)/cols.reduce((a,b)=>a+b,0);const cw=cols.map(x=>x*scale);const labels=['LOGO','BANK','CODE','TYPE','PAYOUT DATES','CONDITIONS','CITY'];let x=m;doc.setFillColor(0);doc.rect(m,tableTop,w-2*m,10,'F');doc.setTextColor(255);doc.setFontSize(6.8);labels.forEach((l,i)=>{doc.text(l,x+2,tableTop+6);x+=cw[i]});doc.setTextColor(0);for(let r=0;r<entries.length;r++){const e=entries[r],sum=entrySummary(e),y=tableTop+10+r*rowH;doc.setFillColor(r%2===0?121:255,r%2===0?218:255,r%2===0?80:255);doc.rect(m,y,w-2*m,rowH,'F');doc.setDrawColor(60);x=m;cw.forEach(c=>{doc.rect(x,y,c,rowH);x+=c});const logo=assets.logos[e.institution];if(logo){try{doc.addImage(logo,'PNG',m+2,y+2,cw[0]-4,rowH-4,undefined,'FAST')}catch(_){}}else{doc.setFontSize(7);doc.setFont('helvetica','bold');doc.text(initials(e.institution),m+cw[0]/2,y+rowH/2,{align:'center'})}x=m+cw[0];const cells=[shortText(e.institution,45),shortText(sum.code,28),shortText(sum.type,18),shortText(sum.timeline,160),shortText(`${sum.payouts}${sum.conditions?`\n${sum.conditions}`:''}`,500),shortText(sum.city,100)];for(let i=0;i<cells.length;i++){doc.setFont('helvetica',i===0?'bold':'normal');const maxW=cw[i+1]-4;let fs=orientation==='landscape'?5.3:5.0;doc.setFontSize(fs);let lines=doc.splitTextToSize(cells[i],maxW);const maxLines=Math.max(2,Math.floor((rowH-4)/(fs*.36*1.1)));if(lines.length>maxLines)lines=lines.slice(0,maxLines);doc.text(lines,x+2,y+3.7,{baseline:'top',lineHeightFactor:1.08});x+=cw[i+1]}}
  doc.setFillColor(255);doc.rect(0,h-footerH,w,footerH,'F');doc.setTextColor(0);doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.text('NoBroker Loans · Master Catalog · Full product terms remain available in the Simple PDF / Excel export.',m,h-10);if(assets.qr)doc.addImage(assets.qr,'PNG',w-20,h-footerH+3,15,15,undefined,'FAST');
}
async function generateRichPdf(recs,stamp){await lazyScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js','jspdf');const {jsPDF}=window.jspdf;const o=state.print.orientation;const doc=new jsPDF({unit:'mm',format:'a4',orientation:o,compress:true});const bg=await fetchDataUrl('assets/rich-background.jpg'),p2=await fetchDataUrl('assets/partner-benefits.jpg'),qr=await fetchDataUrl('assets/partner-qr.png').catch(()=>null);const entries=orderedEntries(recs);const logos={};for(const name of unique(entries.map(e=>e.institution)))logos[name]=await logoForInstitution(name);let w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();doc.addImage(bg,'JPEG',0,0,w,h,undefined,'FAST');doc.setTextColor(0);doc.setFont('helvetica','bold');doc.setFontSize(28);doc.text('MASTER CATALOG',w/2,h*.36,{align:'center'});doc.setFontSize(16);doc.text(monthStamp(),w/2,h*.45,{align:'center'});const nm=$('#cover-name').value.trim(),dg=$('#cover-designation').value.trim();if(nm||dg){doc.setFontSize(10);doc.text([nm,dg].filter(Boolean).join(' · '),w/2,h*.54,{align:'center'})}doc.addPage('a4','landscape');w=doc.internal.pageSize.getWidth();h=doc.internal.pageSize.getHeight();doc.addImage(bg,'JPEG',0,0,w,h,undefined,'FAST');doc.addImage(p2,'JPEG',0,0,w,h,undefined,'FAST');const a=auditText(stamp);doc.setFillColor(255);doc.setDrawColor(0);doc.roundedRect(8,h-18,86,11,2,2,'FD');doc.setTextColor(0);doc.setFontSize(6.5);doc.text(`Public IP: ${a.ip}   •   ${a.date} ${a.time}   •   ${a.tz}`,11,h-11.5);const per=o==='landscape'?5:6;for(const key of state.sequence){const group=entries.filter(e=>e.sequenceKey===key);for(let i=0;i<group.length;i+=per){doc.addPage('a4',o);await drawRichGroupPage(doc,group.slice(i,i+per),key,{bg,qr,logos},o)}}return doc;}

async function downloadExcel(recs,stamp){await lazyScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','XLSX');const a=auditText(stamp),wb=XLSX.utils.book_new();const rows=[['Master Catalog',monthStamp()],['View',`${currentTier()} · ${state.factor}%`],['Public IP',a.ip],['Download Date',a.date],['Download Time',a.time],['Timezone',a.tz],[],['Institution Name','Code','Gross/Net','Product Group','Product Type','Sub-Product / Variant','Calculated Payout','Payout Timeline','Payment Type','Applicable Cities','Top Slab Loan Val.','Payout Capping','Clawback']];orderedEntries(recs).forEach(e=>e.records.forEach(r=>rows.push([r.institutionName,r.code,r.grossNet,PRODUCT_LABELS[r.productGroup]||r.productGroup,r.productType,r.variant,r.payoutDisplay,r.payoutTimeline,r.paymentType,r.applicableCities,r.topSlabLoanVal,r.payoutCapping,r.clawback])));const ws=XLSX.utils.aoa_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,`${monthStamp()} Payout Catalog`.slice(0,31));const cond=[['Institution Name','Code','Product','Variant','Payout Conditions','Login Mandate / Process']];recs.forEach(r=>cond.push([r.institutionName,r.code,PRODUCT_LABELS[r.productGroup]||r.productGroup,r.variant,r.conditions,r.loginProcess]));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(cond),'Payout Conditions');XLSX.writeFile(wb,`${fileBase()}.xlsx`);}
async function finalDownload(){const format=$('input[name="download-format"]:checked').value;const recs=selectedRecordsForDownload();if(!recs.length)return;$('#final-download').disabled=true;$('#final-download').textContent='Preparing…';try{const stamp=await getNetworkStamp();if(format==='xlsx')await downloadExcel(recs,stamp);else{const rich=state.user?.role==='shiv'&&state.pdfStyle==='rich';const doc=rich?await generateRichPdf(recs,stamp):await generateSimplePdf(recs,stamp);doc.save(`${fileBase()}.pdf`)}closeOverlay('download-overlay')}catch(e){alert(`Download failed: ${e.message}`)}finally{$('#final-download').textContent='Download';updateDownloadButton()}}

function showScreenshotGuard(){const g=$('#screenshot-guard');g.classList.add('active');g.setAttribute('aria-hidden','false');setTimeout(()=>{g.classList.remove('active');g.setAttribute('aria-hidden','true')},1800)}
function installEvents(){
  $('#search-input').oninput=e=>{state.search=e.target.value;renderAll()};$('#search-clear').onclick=()=>{$('#search-input').value='';state.search='';renderAll()};$('#list-view-btn').onclick=()=>{state.display='list';$('#list-view-btn').classList.add('active');$('#grid-view-btn').classList.remove('active');renderCatalog()};$('#grid-view-btn').onclick=()=>{state.display='grid';$('#grid-view-btn').classList.add('active');$('#list-view-btn').classList.remove('active');renderCatalog()};$('#select-visible').onclick=()=>{groupBanks(visibleRecords()).forEach(b=>state.selected.add(b.name));renderAll()};$('#clear-selection').onclick=()=>{state.selected.clear();renderAll()};$('#login-btn').onclick=()=>openOverlay('auth-overlay');$('#logout-btn').onclick=logout;$('#auth-submit').onclick=login;$('#auth-password').onkeydown=e=>{if(e.key==='Enter')login()};$('#show-password').onclick=()=>{const p=$('#auth-password');p.type=p.type==='password'?'text':'password';$('#show-password').textContent=p.type==='password'?'Show':'Hide'};$$('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)closeOverlay(o.id)});$('#download-fab').onclick=openDownloadStudio;$('#download-city-filter').onchange=()=>{renderSequencer();schedulePreview()};$('#factor-input').onchange=refreshForFactor;$('#factor-input').oninput=()=>{$('#factor-input').value=Math.min(currentCap(),Math.max(0,Number($('#factor-input').value)||0));};$$('input[name="download-format"]').forEach(x=>x.onchange=()=>{updateDownloadButton();renderPreview()});$$('input[name="pdf-style"]').forEach(x=>x.onchange=e=>{state.pdfStyle=e.target.value;updateDownloadButton();renderPreview()});$$('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));['s-margin','s-font','s-line','s-field-gap','s-block-gap','s-header','s-footer','s-qr-gap','s-card-padding','s-section-gap'].forEach(id=>$('#'+id).oninput=readPrintInputs);$$('input[name="orientation"]').forEach(x=>x.onchange=readPrintInputs);$('#reset-print-settings').onclick=()=>setPreset('compact');$('#network-consent').onchange=updateDownloadButton;$('#refresh-preview').onclick=renderPreview;$('#final-download').onclick=finalDownload;
  document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.overlay.open').forEach(o=>closeOverlay(o.id));const screenKey=e.key==='PrintScreen'||((e.metaKey||e.ctrlKey)&&e.shiftKey&&['3','4','5','s','S'].includes(e.key));if(screenKey){e.preventDefault();showScreenshotGuard()}});
  window.addEventListener('keyup',e=>{if(e.key==='PrintScreen')showScreenshotGuard()});
}
async function init(){loadPrintSettings();installEvents();const restored=await restoreSession();await loadCatalog(restored?'t1':'public');}
init();
})();
